# Drabme {-#drabme}

[Drabme](#drabme) is an acronym for *Drug Response Analysis to Boolean Model Ensembles*.
This module performs a combinatorial drug response analysis using the boolean models [generated by Gitsbe](#gitsbe-output) in order to evaluate and identify the synergistic drug combinations.

The code of the package is available in Bitbucket.

This documentation is for the software version ``r drabme_version``

## Description {-#drabme-description}

Initially, [Drabme](#drabme) uses an ensemble of boolean models and a list of drug [perturbations] to generate *perturbed* models.
This means that for every combination of a boolean model generated by [Gitsbe](#gitsbe-output) and a drug perturbation [given](#perturbations), a new model is created by finding the targets of the perturbation's drug(s) (see [drug panel]) and permanently changing their respective boolean equations to either `false` (when the drug is *inhibiting* its target - most common case scenario) or `true` (when the drug is causing the *expression* of its target).

Then, the attractors of the perturbed models are calculated and a *global output response* value is computed for each perturbed model using the [model outputs](#modeloutputs) and Equation No. \@ref(eq:modeloutputs).
Thus we simulate the effect that each perturbation has on different versions of the cell network system under test (defined originally as a [Gitsbe input](#gitsbe-input)).
The perturbed models' response values can now be used to assess which drug *combinations* are synergistic.
Next, we focus our discussion on **two-drug combinations** for ease of understanding, but note that Drabme supports the synergy evaluation of higher-order drug combinations as well.

---

The most simple mathematical models that are used to evaluate if two drugs are synergistic or not, are the *HSA* (Highest Single Agent) and *Bliss Independence* [@BLISS1939] models.
The simplicity of these models lies in the fact that they are *effect*-based (or equivalently *response*-based in our case ^[Note that the term *effect* is used complementary to the term *response*, i.e. the higher the effect of the drug, the smaller the [output response or viability](#modeloutputs-tip), which is exactly what the calculated *global output responses* of the perturbed models are]) and do not depend on the dosages of the drugs tested (like *Loewe*'s model for example [@Loewe1928]).
Thus, they fit perfectly with the simulation data Drabme produces - i.e. the perturbed models' response values.

In order for these mathematical models to classify two drugs as synergistic (or not), they define an expected *additive* response that the combination should have if the two drugs *are not interacting* with each other (they are neither synergistic or antagonistic - their effects are simply *added*).
**If the (predicted or observed) combined response is lower ^[Again, *higher* if we are talking about *effects*] than the additive one for a particular tested model/system, a synergy is called** (if higher, then an antagonism).
The *HSA* model for example, defines the additive response as the minimum of the two single-drug perturbed model responses ^[On the other hand, *Bliss Independence* defines as the additive response the *product* of the two single-drug perturbed model responses. So it's a more strict model for synergies].
So, when the output response of the two-drug perturbed model is lower than the minimum of the two single-drug perturbed models, the two-drug combination acts synergistically upon that particular model.

The assessment of synergies in [Drabme](#drabme) is done in two ways: **model-wise** and **ensemble-wise** (using *HSA* or *Bliss*, see [configuration options](#drabme-config)).
In the **model-wise** approach, for each drug combination, we find and compare the number of models that predicted it as synergistic vs the number of models that predicted it as antagonistic (using for example the *HSA* method as described in the previous paragraph).
In the **ensemble-wise** approach, for each drug combination, we find the two average single-drug responses as well as the average response for the drug combination (from the collection of models at our disposal ^[Actually, from all the models that had attractors for the specified perturbations (single or double)]) and use the *HSA* (*Bliss*) model on these ensemble-wise values.
The *HSA-exceed* (*Bliss-exceed*) value - i.e. how much lower was the average combination response value from the minimum of the two average responses of the single-drug perturbed models or from their product in the case of *Bliss* (per drug combination tested) - is one the [main outputs of Drabme](#drabme-output).
The more negative that value is, the more synergistic the drug combination is *ensemble-wise* and vise-versa (the more positive, the more antagonistic).

## Installation and Usage {-#drabme-install}

### Install {-}

Prerequisites: `maven 3.6.0` and `Java 8`.

First, install [Gitsbe](#gitsbe).
Then:
```
git clone https://github.com/druglogics/drabme.git
cd drabme
mvn clean install
```

:::{.note}
Note that [Drabme](#drabme) calculates attractors for the boolean models it generates using either the [BNReduction tool](https://github.com/alanavc/BNReduction) [@Veliz-Cuba2014], the [BioLQM](https://github.com/colomoto/bioLQM) Java library [@Naldi2018]  or [the Most Permissive Boolean Networks](https://github.com/pauleve/mpbn) framework [@Pauleve2020].
BioLQM is included by default in the code.
The BNReduction and MPBN scripts have to be manually installed following the [respective documentation](https://github.com/druglogics/druglogics-dep#readme).
:::

### Example {-#drabme-example}

The recommended way to run Drabme is to use it's `Launcher`.
From the root directory of the repo run:
```
cd example_run_ags
java -cp ../target/drabme-`r drabme_version`-jar-with-dependencies.jar eu.druglogics.drabme.Launcher --project=test --modelsDir=models --drugs=toy_ags_drugpanel.tab --perturbations=toy_ags_perturbations.tab --config=toy_ags_config.tab --modeloutputs=toy_ags_modeloutputs.tab
```

or run the `mvn` profile directly (same input as the command above through the `pom.xml`):
```
mvn compile -P runExampleAGS
```

### Inputs {-#drabme-input}

Running the Drabme `Launcher` with no parameters, generates a **usage message** with the available options.
The **required** parameters are:

- `--modelsDir`: A `models` directory with files that were [generated by Gitsbe](#gitsbe-output) (the files are boolean models in `.gitsbe` format)
- `--drugs`: [drug panel file](#drug-panel)
- `--modeloutputs`: [model outputs file](#modeloutputs)
- `--config`: [configuration file](#drabme-config)

The **non-required** parameters are:

- `--project`: the project name which is used as the name of the directory where the [outputs](#drabme-output) will be stored.
- `--perturbations`: [perturbations file](#perturbations)

### Outputs {-#drabme-output}

The expected outputs of Drabme's `Launcher` can be classified into 3 categories of generated files (see also [Description](#drabme-description)):

1. **Model-wise** results
    - A model-wise *responses* file (for every tested [perturbation](#perturbations), all models' [global output responses](#eq:modeloutputs))
    - A model-wise *synergies* file (for every drug combination tested, the number of models that found it synergistic vs non-synergistic)
2. **Ensemble-wise** results (or **perturbation-wise**)
    - A ensemble-wise *responses* file (for every tested [perturbation](#perturbations), the average response of all models that had a global output response - i.e. had an attractor ^[This is just the average value of the data in the **model-wise** *responses* file])
    - A ensemble-wise *synergies* file ^[One of the most important outputs of Drabme. The [druglogics-roc](https://github.com/druglogics/druglogics-roc) R shiny app was built to take the results from this output file and produce a ROC & PR curve.] (for every drug combination tested, a *synergy score* indicating how much synergistic that combination was - a more negative number means more synergistic, a positive number indicates antagonism)
3. A **model predictions** file
    - For every model and drug combination tested, this file stores a value that indicates if the corresponding drug combination manifests *synergistically* or not in the respective model.
    The three possible values are: $0$ = no synergy predicted, $1$ = synergy predicted, $NA$ = couldn't find attractors in either the drug combination inhibited model or in any of the subset-drug inhibited models (this output value is impossible when trapspaces are used for the [computation of the attractors](#attractor-tool)).

::: {.note}
It is for the better that all input files are on the same directory as in the [example above](#drabme-example). 
In any case, the directory with all the output files when running the `Launcher` will be in the same path as the configuration file.
:::

## Drug Panel {-}

The drug panel is a *tab-delimited* file that stores information about the drugs that Drabme will test on it's [input models](#drabme-input). 
In each line, a drug name is given along with the name of its targets and the effect that drug has on them.
The *effect* must be either the *inhibits* or *activates* keyword and the targets must be in the [initial network](#gitsbe-input) otherwise there is an error.

An example of a drug panel file is the following:

:::{#drugpanel-example .blue-box}
A &emsp; **inhibits** &emsp; A1  
B &emsp; **inhibits** &emsp; B1 &emsp; B2  
C &emsp; **activates** &emsp; C1
:::

`A, B` and `C` are the drug names and `A1, B1, B2` and `C1` the respective targets.

If the user does not specify a [perturbations] file in [Drabme’s input files](#drabme-input) (which is not required), the drugs that are listed in the drug panel (above example: `A, B` and `C`) are used to generate all possible combinations of perturbations up to the size number specified in the [respective configuration](#drabme-config).

## Perturbations {-}

A drug *perturbation* is defined as a **single** or a list of **multiple drugs** that are used upon a cell system.
The perturbations file is a simple file where we write each perturbation in a different line.
The drugs listed in a perturbation are separated by *tabs*.
For example, having the four drugs `A,B,C,D` at our (computational) disposal, we can test the following perturbations using [Drabme](#drabme):

:::{.blue-box .fitcontent}
A  
B  
C  
D  
A &emsp; B  
A &emsp; C  
C &emsp; D  
A &emsp; D  
A &emsp; C &emsp; D
:::

:::{#perturbation-note .caution}
For every higher-order perturbation we want to test, the file **must include the drug subsets in the order they are specified in the perturbation**.
:::

For example, to include the `A,B,C` perturbation (we use commas instead of tabs here) in the example file above, the subsets `A,B`, `A,C` and `B,C` must be also present before (the last is not).
And by saying that *order matters*, we mean that writing `C,B` instead of `B,C` before the `A,B,C` perturbation, will generate an error.
If a user wants to avoid such errors, then he must **not specify** a pertubations file in [Drabme's input files](#drabme-input).
What happens then, is that the drugs listed in the [drug panel] are used to generate all possible perturbations up to the number specified in [Drabme's configuration](#drabme-config).

## Configuration {-#drabme-config}

For a list of options that are common between Gitsbe and Drabme see [General] and [Attractor Tool] options.
We only include here the configuration options that can be used by Drabme alone:

- `max_drug_comb_size`. Example value: $2$.

  This option creates all combinations of drugs from the [drug panel] file **up to and including** the given size.
  This option is only used when there is no [perturbations] file given by the user.
  
  If for example there are **3 drugs in the panel**: `A,B,C` and `max_drug_comb_size: 3` then the following drug perturbations are created (note that the order of the drugs is preserved in the higher-order combinations):
  
  :::{.blue-box .fitcontent}
  A  
  B  
  C  
  A&emsp;B  
  A&emsp;C  
  B&emsp;C  
  A&emsp;B&emsp;C  
  :::

- `synergy_method`. Possible values: `hsa` or `bliss`.
  
  This option indicates which method we should use for the calculation of synergies both model-wise and ensemble-wise.
  Using `bliss`, less synergies are predicted in general.
  For more info, see [Description](#drabme-description).
