---
title: "DrugLogics Software Documentation"
author: "John Zobolas"
date: "Last updated: `r format(Sys.time(), '%d %B, %Y')`"
description: "DrugLogics Software Documentation"
url: 'https\://druglogics.github.io/druglogics-doc/'
github-repo: "druglogics/druglogics-doc"
bibliography: ["references.bib", "packages.bib"]
link-citations: true
site: bookdown::bookdown_site
---

```{r stuff, include = FALSE}
# automatically create a bib database for R packages 
knitr::write_bib(c(.packages(), 'bookdown'), 'packages.bib')

# Package versions
gitsbe_version = "1.3.0"
drabme_version = "1.2.0"
```

# Introduction {-}

This is an online documentation for some of the software packages in the [druglogics GitHub organisation](https://github.com/druglogics/).
It's created using the bookdown package [@bookdown2016].
The following packages are fully documented in this manual:

- [Gitsbe](#gitsbe)
- [Drabme](#drabme)

Other DrugLogics-related packages (documented in their respective repositories) are:

- [druglogics-synergy](https://bitbucket.org/asmundf/druglogics-synergy/src/master/)  
A small package which runs sequentially Gitsbe and then Drabme, to make it easier for users to execute/test the two pipeline packages in one go.
- [druglogics-roc](https://github.com/druglogics/druglogics-roc)  
R shiny app that was built to use the results from Drabme's [ensemble-wise synergies output file](#drabme-output) and produce a ROC (Receiver Operator Characteristic) and a PR (Precision-Recall) curve in order to assess the performance of Drabme's synergy classifier/predictor.
- [abmlog](https://github.com/druglogics/abmlog)  
A generator of all possible boolean models with AND/OR-NOT link operators.
- [emba](#emba)

:::{.caution}
The Java-based packages are currently in **private BitBucket repositories** and will be publicly released in Github when the relevant publication gets accepted :)
:::
